### PR TITLE
Refactored map

### PR DESCRIPTION
**Pull request by terribium**
Hi!

Here is refactored map. There are so many changes to code so I won't explain these here. All changes from your master branch are included up to commit #197 ("Move declarations into a headed file") - currently latest commit.

Only change to 'dump1090.c'-file is at https://github.com/bdavenport/dump1090/commit/3000baf184aaab9d5a64292e27c8ae440c5ce542 where I removed unused conversion from aircraftsToJson() at dump1090.c-file.

Screenshot of new map
tutka

### CODE REVIEW

**Comment by terribium** [comment]
Easiest way (yet kind a dirty) to fix merge conflicts in 'public_html'-directory is to overwrite conflicting files with fresh copy from bdavenports master branch.

**Comment by hhm0** [comment]
Hi,

Hope this is a good method of updating/communicating-to all the web UI people.

I made a pull request with a bunch of (mostly internal) changes - #17.

Enjoy :-) Hope everyone likes it.

P.S. I would like a mobile interface. Idea for now is to just have tabs for each of map, table, and detail, instead of them all together on same screen (similar to android <a href="http://developer.android.com/guide/components/fragments.html">fragments</a>). How would I go about this? Should the web UI be migrated from JQuery UI to Bootstrap, or maybe code something responsive (css media queries) (or maybe the mobile should just have its own html page, reusing existing code between files)?

Thanks.

P.P.S. antirez <a href="https://github.com/antirez/dump1090/commit/03759a3eb01f41f322e393f358ef82430857ff3d">added altitude colors</a>, maybe we can work off his code for colored altitude lines.

**Comment by mindlesstux** [comment]
@hhm0,
Iv had an idea for mobile interface as well, mainly centered around a tablet screen size, that reuses code to a degree.  Though I am focused on reworking the version that you worked on to be a little more sleeker so to speak (http://adsb.mindlesstux.com - to sorta see where I am headed).  I am experimenting with jquery layout and various jquery table plugins to remove some of the html the js code generates.

I will have to look at what antirez imported to that as that is an option I would like to put in the new version.  Except make it for altitude, speed, carrier colors (and or all planes of same carrier), or highlighted plane given that all other trails would be shown but low opacity and grey in color, maybe only last 10 points too.

**Comment by hhm0** [comment]
On 6/2/14, Brian Davenport notifications@github.com wrote:

> @hhm0,
> Iv had an idea for mobile interface as well, mainly centered around a tablet
> screen size, that reuses code to a degree.  Though I am focused on reworking
> the version that you worked on to be a little more sleeker so to speak
> (http://adsb.mindlesstux.com - to sorta see where I am headed).  I am
> experimenting with jquery layout and various jquery table plugins to remove
> some of the html the js code generates.

Cool. I am interested in phone-size mobile interface; that would be a
good thing about using bootstrap/responsive-web, that the code can
work for multiple UI types with minimal changing.

> I will have to look at what antirez imported to that as that is an option I
> would like to put in the new version.  Except make it for altitude, speed,
> carrier colors (and or all planes of same carrier), or highlighted plane
> given that all other trails would be shown but low opacity and grey in
> color, maybe only last 10 points too.

Ok, neat; I checked out how the UI is there - it changes the plane
icon color to varying amounts of yellow to white based on the
altitude.

Carrier colors etc. sounds really neat! Trails for multiple planes at
a time would also be nice.

**Comment by hhm0** [comment]
For mobile, I have been thinking of a simpler codebase, using something like CSS media queries and some element hide/show code.

Config info from server can be useful, thinking of having a dynamically-generated JSON page which can tell the client the server's settings, if the server is allowing this. Then these can be used as defaults; for example, receiver location, metric units settings. These values may be used together with values set in `public_html/config.js` and by the client in the web-ui.

Another thing which would be awesome is an extension system; for example to have custom columns in the table, or custom plane info links, custom map, or anything else. This is already done very rudimentarily by `public_html/extension.js`; however, this would allow reentrant extending. These extensions can then be selectively enabled by the user, and some can come prepackaged. This allows all sorts of custom interfaces, according to personal preferences.

**Pull request merged**
