### PR TITLE
Avoid javascript memory leaks on web page

### PR DESCRIPTION
**Pull request by bovine**
When leaving a web browser open for an extended period of time, the memory usage of the browser will continue to increase as table rows for each new aircraft is added or removed.

The largest part of this leak appears to be caused by adding a new click event handler for each row, so this was changed to use a more conventional onclick handler with a javascript function that is defined globally once.

### CODE REVIEW

**Comment by MalcolmRobb** [comment]
Bovine,
This doesn't work on IE8 and IE9. It does work on IE11. I realise that it's probably some problem with the older browsers, but since IE8 is my minimum baseline (I still support Win2K and XP) I can't accept this push as is.
Thanks
Malcolm

**Comment by bovine** [comment]
Okay we will investigate. Were you receiving a javascript exception on IE8/9?

**Comment by MalcolmRobb** [comment]
No - No exceptions. The planes display correctly on the map, but the list/table does not get populated with any entries. The headings are there, just no listings.
Clicking on the aircraft ICON does populate the detail fields at the top of the pane though
Cheers
Malcolm

**Comment by hhm0** [comment]
#18 also fixes this (but conflates the fix with other changes), but differently, by using DOM elements instead of html code.

This is actually what got me to start working on #18 :-)

I could not trace down the leak source like you could, @bovine :-). So instead I just changed the whole part :-).

And I did not test #18 on IE so far, @MalcolmRobb; I hope we can get some kind of fix in for the leak that works with IE, though, since I think solving this makes the web UI a lot more robust.

**Pull request closed without merging**
