### PR TITLE
Fix a crash when an outbound client is closed in response to reading a remote message

### PR DESCRIPTION
**Pull request by mutability**
When we read from some client A, we may end up forwarding a message to other
clients. If we forward to some client B and there is a write error, then
we close B and remove it from the client list. However, if before this happened
A->next == B, then the read loop will still be holding on to a pointer to B,
and we crash.

As it's unpredictable what clients could be closed at what point, the simplest
approach is to retain closed clients in the list until we are at a point where
we know there are no stray pointers on stack, and only then modify the list.
This also simplifies anything that has to loop over clients, as it doesn't need
to worry about the current client being freed under it.

### CODE REVIEW

**Comment by hhm0** [comment]
I also found and fixed that bug :-) (see #33).

I probably should have made it into a separate pull, though, since its a separate concern from that.

**Comment by MalcolmRobb** [comment]
I think this issue was resolved in #33, although in a slightly different way. If there is something I've missed let me know, but as it stands I'll just close this without implementing it.
Thanks

**Comment by mutability** [comment]
From a look at the current code I don't think #33 is sufficient: modesSendAllClients() may still free clients (that were closed in a previous write), and there are indirect callers of modesSendAllClients() e.g. modesReadFromClients() that may have a pointer to that client.

The unlinking/freeing of clients needs to happen at a controlled point where we know there's nothing on stack holding a pointer; modesSendAllClients() is not a safe point to do this.

**Comment by hhm0** [comment]
@mutability, I see what you're saying.

If I remember correctly, the reason that it my version only collects the connections in `modesSendAllClients` in  is because in the current code, all sockets are  safe to be freed at that point (and also my main goal with those fixes was just to get the fds to stop leaking and `dump1090` would be stable when run for a while, and this fix was just a small part of that, so I just applied a quick fix); however, like you mentioned, if the code were to be changed, this would not necessarily be the case, and we may as well prevent this error before it pops up.

Your code looks good to me, the only thing is, that `modesFreeClient` doesn't really free the client anymore! :-) Perhaps `modesFreeClient` can be only for internal use, and calls to it replaced with calls to something like `modesCloseClient` in my code.

Other than that, as long as any marked-closed sockets will be freed frequently enough (it looks like your code does this about once per second, which I guess is enough) that they won't pile up enough to use lots of resources (like ram, fds), i am happy with this.

**Comment by mutability** [comment]
I did exactly that close/free rename in #50, conveniently enough :)

I think the issue does already exist even without code changes - modesSendAllClients can already be called with callers holding pointers - when processing a remotely-received message from an input socket that is being forwarded to output sockets. (That's the case that I had crashes with that lead me to fix this originally)

**Comment by mutability** [comment]
For the sake of completeness - the changes in this pull request aren't directly useful any more, but I have rolled them up into my current changes in #50.

**Pull request closed without merging**
