### PR TITLE
Web client

### PR DESCRIPTION
**Pull request by terribium**
Most changes are at client side. Only modifications on 'dump1090.c'-file are 2 new variables to json-export.

### CODE REVIEW

**Comment by MalcolmRobb** [comment]
Thanks, if no-one objects in the mean time, I'll merge you code tomorrow.

**Comment by mindlesstux** [comment]
The only thing I question is the re-sizing of the map, is that really necessary?
It should be possible to set a static width on the info div, then set map canvas's margin-right to be the same width as the info div.  Eliminating the javascript.

**Comment by mindlesstux** [comment]
terribl, I am not sure why you added the valid position flag, can you elaborate a little on that?  (I might be missing the 400 ton elephant in the room as to why.)

You might also get some use of the alterations of the fetchData function I have been hacking at, live @ http://raspberry.mindlesstux.com/dump1090/script.js

**Comment by terribium** [comment]
ResizeMap-function is apparently not needed. I have been trying to set **right**-margin. I'll look into that.

Validposition is to check if coordinates are given. (same as validtrack)

``` javascript
if (plane.lat != 0 && plane.lon != 0) {
```

Code above checks if coordinates are not (0, 0) yet in earth there is place where this if-returns false false.

**Comment by mindlesstux** [comment]
it's margin-right. ;)
http://raspberry.mindlesstux.com/dump1090/ - just put that live, static width of 390px on the right.

**Comment by terribium** [comment]
Since yours css- and html-files are working great, I'll just copy those - and your fetchData() ;)

@MalcolmRobb Do not merge yet - we're making these changes first... I try to commit later today or tomorrow (UTC+3).

**Comment by mindlesstux** [comment]
@terribl 
Dont forget to reset the lat/long and view distance back to what they were ;)  I forked and seeing what I can do in the way of enhancements I came up with, list @ https://github.com/bdavenport/dump1090/issues

**Comment by terribium** [comment]
Now this should be ok to go.

For some reason there is sometimes small lag when selecting planes from table... I don't know why.

@bdavenport Ok with you?

**Comment by mindlesstux** [comment]
It reads ok to me, did this patch work for you @terribl ?

I wont be able to test it or work on the code till my lunch hour (1200 @ UTC -0400).  Though I would like to devote my lunch hour to re-coding the table building function I already wrote.  We had some code at the office that sorted tables by columns, I want to throw that in, but I'll make my own pull request for that.

**Comment by terribium** [comment]
Works great! Thank you :)

@MalcolmRobb Now we are ready with this pull request. Use the force

**Comment by MalcolmRobb** [comment]
Ok Guys, cross your fingers here goes...

**Pull request merged**
