### PR TITLE
My modifications... I like them.

### PR DESCRIPTION
**Pull request by ekkithump**
Hi, 
  I'd been slowly making  a number of modifications to my fork of antirez's
code-base which I've now re-written and improved with a bit more thought onto 
a fork of your repo.
I did rather apply them all at once though, so most of my commits squashed here
are bug-fixing / re-factoring rather than applying the different extra features in a
logical manner.  Sorry it's such a big patch, that's why.

New Features:
-   Map gets centred on user's runtime-specified position
-   Calculation / display of range, azimuth and elevation of each aircraft.
-   Azimuth / lowest angle file (for plotting e.g. with gnuplot) 
-   Azimuth plot(s) on map
-   Adjustable polling of server
-   Server remembers partial trails of aircraft
-   Selection of trail display : selected/active/reapable & reaped
-   Browser incrementally calculates (and shows) a guess of plane's location
  based on speed/direction if updates are slow.

Rationale / description:
The azimuth file contains in one degree intervals, both maximum distance (km) 
and lowest elevation. The file is updated by default every 10 minutes, 
but only if there have been changes.

I've not yet tried to adjust the interactive display for range and elevation, on 
this fork though I had that originally.  When the sky is clear it helps spot an 
approaching plane.

The javascript can pull in the azimuth plot multiple times so you can see e.g. if 
there have been changes in the last hour. (any pulled in plot may be deleted)

I like to see trails, so I can see at a glance if there's a plane doing
something interesting. e.g. been put in a stack where I expected it to just
land. Sometimes I'm away and I like to see where the planes have been,
hence all the trail display options.

When viewing, I find one update every 2 to 5 seconds is normally sufficient.
If I'm reading another tab, I don't see why the browser should waste it's and
the server's CPU time updating every second.  If the window loses visibility 
the updates reduce to 45 seconds.

In that time, of course, the planes can move quite a way.  Hence the server now
keeps a small (runtime-configurable) cache of old positions. The change to
the server code to make it remember e.g. altitude would be 1 changed #define
and 2 more lines.

This also means that if the browser has only just started then trails are still
available. To avoid wasted CPU cycles on browser & server,  the browser tries
to guess a sensible number of positions, rather than the whole cache.

Guesses: My kids get really confused by planes just sitting there while another
seemingly runs into it. If a plane hasn't moved in >5 seconds, the browser starts
calculating and displays an arrow showing where the plane probably is. 
I don't know if it's noise-related or just normal, but I frequently see a plane's heading 
being updated but no new positions for > 30 seconds, and I'm pleasantly surprised how 
accurately the guesses work out, even when the plane turns.
Maybe the guess's label should show the flight number, but so far it just gives the hexcode.

### CODE REVIEW

**Comment by mindlesstux** [comment]
Do you have a public URL example of this?

I like several of your ideas.

**Comment by ekkithump** [comment]
Sorry, I can send some screen-shots if you like, but I'm behind 
several layers of NAT from my ISP.

**Comment by mindlesstux** [comment]
That is ok, was just wondering if you did.  Would save me a little time when my next free time block shows up.

**Comment by ekkithump** [comment]
I've just patched my patch... A double insert had happened somehow and I'd forgotten to update help and some comments.  

I've also added in a fix for something that's been annoying me.. There's a visible flash
on my son's R-pi when the screen refreshes. That happening every second is bad enough, but 4 times a second is really disturbing. Hence I've added a --interactive-refresh option.

**Comment by frankvdh** [comment]
Sorry, I'm new here and struggling to figure out what's what at the moment (and can't see how to create a new conversation thread)... can someone please enlighten me?

What is the difference between this dump1090 and the (I assume) base RPi version at http://www.satsignal.eu/raspberry-pi/dump1090.html and the (I assume) base dump1090 version at https://github.com/antirez/dump1090? Is there some process for bringing changes made to either of those versions to this one? Or vice versa?

I'm looking to run dump1090 on a RPi, and output the aircraft positions to XCSoar which will be running on my Android phone. I haven't quite decided between Bluetooth, USB, and Wifi for that connection. I think I'd just have dump1090 output to stdout, and pipe that to another program which would send it to the phone. Or is there an easier way? Which version of dump1090 should I use?

Thanks

Frank

**Comment by ekkithump** [comment]
On Tue, Feb 04, 2014 at 01:48:31PM -0800, frankvdh wrote:

> What is the difference between this dump1090 and the (I assume) base RPi
> version at http://www.satsignal.eu/raspberry-pi/dump1090.html and the (I
> assume) base dump1090 version at https://github.com/antirez/dump1090? Is
> there some process for bringing changes made to either of those versions to
> this one?  Or vice versa?

From my understanding, 'antirez' (can't remember his real name) came up
with the original version. The HTML display of that does not have the table,
or clocks, or squawk decoding, and has simple triangles for the planes.

The version pictured on  www.satsignal.eu is Malcolm's version.
The code-bases have diverged (minor tweaks to antirez's version, major 
developments on Malcolm's, including decoding more packets and 
splitting the original single .c file into several dealing with different
functions.) Malcolm's version shows a trail only for the selected plane.

The animation on www.satsignal.eu  is of planeplotter, which can, I believe,
be fed with data from dump1090.

My pull request (which you replied to) adds trails to all planes, azimuth plots
and various tweaks intended to reduce CPUload (e.g. refreshing the screen a
little less often).

FYI, I've had it running on a RPi for about 9.5 days, in which time it's eaten
5.4 days CPU time, decoding mode A&C as well as S, mostly not feeding a 
web server, but feeding flightradar24.
I don't know how much load varies based no how busy your sky is. I get a peak
of 20 planes on-radar at once.

Hope that helps.
David

**Pull request closed without merging**
