### PR TITLE
link to FlightAware for flight details

### PR DESCRIPTION
**Pull request by bovine**
This just adds a second link on the side panel to let the user view the flight's information on FlightAware, which sometimes has more information about a flight than FlightStats, particularly general aviation aircraft.

### CODE REVIEW

**Comment by hhm0** [comment]
<b>EDITED</b> to update codes.

It seems that a possible disadvantage inherent in having multiple links to similar sites may be, that there are many sites which provide some form flight tracking, and the UI would end up eventually being cluttered with tons of links! :-)

An alternative to adding additional links, can be to have a customizable URL for flight information in `public_html/config.js` (whose defaults could technically be made to be modifiable from the web UI, at some point, and then these could be configured by the client user); for example...

```
#FlightInfoLinkUrl = 'http://www.flightstats.com/go/FlightStatus/flightStatusByFlight.do?flightNumber={flight}';
#FlightInfoLinkLabel = 'FlightStats';
FlightInfoLinkUrl = 'http://flightaware.com/live/flight/{flight}';
FlightInfoLinkLabel = 'FlightAware';
```

...and in the code which renders the links, `{flight}` could be replaced with the flight's callsign, perhaps like so...

```
html += '&nbsp;<a href="' + FlightInfoLinkUrl.replace("{flight}", selected.flight) + '" target="_blank">[' + FlightInfoLinkLabel + ']</a>';
# the Url and Label should really be added using the DOM, or be escaped, to 
#   protect from malicious inputs
```

Enjoy, and take with a grain of salt, if you so please :-).

**Comment by hhm0** [comment]
Just submitted #17, it implements adding elements by using DOM, therefore, even if the user can set the link, it is escaped, to remove code injection possibilities; this is even better for making this link configurable.

Also, the extension system can be enhanced to have a multiple links hook; I would like to implement something similar to add table columns for each plane myself, G-d willing :-).

**Comment by hhm0** [comment]
I personally like this addition.

It would be awesome if it can be reopened! :-)

My <a href="https://github.com/MalcolmRobb/dump1090/pull/13#issuecomment-43987129">earlier comment(s)</a> no longer applies, since #30 got pulled, so there are now already multiple links.

**Comment by hhm0** [comment]
I personally like this addition.

It would be awesome if it can be reopened! :-)

My <a href="https://github.com/MalcolmRobb/dump1090/pull/13#issuecomment-43987129">earlier comment</a> no longer applies, since #30 got pulled, so there are now already multiple links.

My <a href="https://github.com/MalcolmRobb/dump1090/pull/13#issuecomment-44769046">other comment</a> does not either apply yet, since the extension system spoken of is not ready, even with #18 applied.

**Comment by bovine** [comment]
open reopening

**Comment by MalcolmRobb** [comment]
Done. I think we can stand 3 or 4 of the more common flight lookup services without too much issue.

**Pull request merged**
