### PR TITLE
DF 18 / Control field 5 cluttering interactive display

### PR DESCRIPTION
**Pull request by wiseman**
(This is a dummy commit/PR.  Sorry, I would open an issue but the repo doesn't have issues.  Let me know if there's a better place to talk about this sort of thing.)

In Los Angeles I'm currently getting a lot of messages like this:

```
*95c60bf13b4db286b30fc180d20d;
CRC: 000000 (ok)
DF 18: Extended Squitter.
  Control Field : 5 (TIS-B relay of ADS-B message with other address)
```

I also see a lot of what look like dozens of bogus entries in the interactive display:

```
C6021C  S                                                        50     3   21
C60979  S                                                        53    10   18
C6067B  S                                                        49    22    2
C601EB  S                                                        49    18    5
C60A6C  S                                                        53    12   17
C60795  S                                                        41     4   18
C601DA  S                                                        52    17    1
C60C20  S                                                        46    10   19
C6092E  S                                                        47    24    1
C609B1  S                                                        47     9   19
C60B19  S                                                        44    28    1
C60FC6  S                                                        49    13   17
C6078C  S                                                        51    11   18
C601B7  S                                                        48    12   18
C60250  S                                                        44    21    2
C60130  S                                                        49    27    1
C60BF5  S                                                        51     3   23
C60652  S                                                        50     6   18
...
```

I don't know the details of DF 18, but the code that prints DF 18 doesn't seem to think there's an address in the message, due to the `mm->ca` guards here:

```
        if ((mm->ca == 0) || (mm->ca == 1) || (mm->ca == 6)) {
            if (mm->ca == 1) {
                printf("  Other Address : %06x\n", mm->addr);
            } else {
                printf("  ICAO Address  : %06x\n", mm->addr);
            }
```

But maybe the interactive display (and web API) is somewhat blindly showing the entries with the address, which is invalid?

### CODE REVIEW

**Comment by MalcolmRobb** [comment]
John,
I think TIS-B is used in the USA by some FAA ATC units to broadcast the position of non ModeS/ADSB equipped aircraft. Basically, then ground radar station allocates a 'random' number (from within an FAA reserved block) to radar tracks, and then broadcasts a DF-18 so that other aircraft become aware of them - for TCAS collision avoidance. 

What I suspect you are seeing is these TIS-B 'codes' allocated by ATC to local light aircraft/gliders that aren't ModeS/ADSB equipped. Are you close to a radar head/ground station? The address isn't 'invalid' as such, it's just temparerily allocated to a radar track.

I don't think we use TIS here in the UK, so it's difficult for me to debug that kind of stuff.
Cheers
Malcolm

**Comment by MalcolmRobb** [comment]
I'll close this pull. You can still continue to post follow-up messages here if you wish.
Cheers
Malcolm

**Comment by wiseman** [comment]
OK, thanks.  If you happen to have any pointers to docs on DF18 let me know, maybe I can take advantage of being able to receive these packets to work on the code a bit.

**Comment by mutability** [comment]
Doc 9871 seems to cover the TIS-B formats. CF=5 appears to just use essentially the same formats for position/velocity as for regular DF 17 extended squitter, as far as I can tell.

**Comment by mutability** [comment]
With the limited data I have (a grand total of 2 messages..) they both decoded plausibly if I treated them the same as DF 17. So you should be able to just expand the guard to allow mm->ca==5 too (there are a couple of places that need it) and hopefully you'll see useful results.

**Pull request closed without merging**
