### PR TITLE
Table sort & bit cleaner look with larger tables on smaller screens

### PR DESCRIPTION
**Pull request by mindlesstux**
Adds a bit of sorting to the table by clicking column headers

Also made the design work for lower resolution monitors, especially when the list has 20+ planes.

### CODE REVIEW

**Comment by terribium** [comment]
Works great!

Just to make sure that people know that column headers are click able I would change cursor from text to pointer. `cursor: pointer;`

**Comment by mindlesstux** [comment]
Added the suggestion there @terribl 

/me goes back to work on the next pull request regarding the signal levels in the interactive screen.
Any idea what the max signal is?  I would assume 256. Also which way is the better number? closer to max or closer to 0 indicate the stronger signal?

**Comment by mindlesstux** [comment]
Also do you guys mind if I code up something that is more of a add on externally to the dump1090 and its web interface?  I have been wanting to get the flight path trails on the map for some time.  There are a couple of ways about doing this, one is to keep a running history in javascript and have a reaper function clear out the old planes.  This would only be useful for long running page views.  The other option is to build an external program/script to store the data then use same program/script or another to produce the proper KML files.  Right now I am working on option 2 as it allows the most flexibility.

**Comment by terribium** [comment]
Signal strength is 'unsigned char'-type so it should be 0-255 and higher value means stronger signal.

**Comment by MalcolmRobb** [comment]
Sorry for the delays guys - been tied up on family stuff for the past week. I'll attempt to get everything merged in the next day or two. 

As terribl says, Signal strength is an unsigned char, so ranges from 0 to 255. Higher is stronger. It's not very linear though - distant signals typically show as 4 or 5, Things have to be within about 10-20 miles to get into double figures for me, and the highest i've noted is about 170 when a helicopter was passing my window (perhaps 200 yards).

**Pull request merged**
