### PR TITLE
Web server tweaks

### PR DESCRIPTION
**Pull request by terribium**
Here are few web server tweaks.

Most noticeable change is moving file 'gmap.html' to own 'public_html'-directory and splitting it up to html-, javascript- and css-files. This should make editing web-interface easier and away from 'dump1090.c'-file.

### CODE REVIEW

**Comment by terribium** [comment]
And it saves and restores last used map position to/from localStorage :)

**Comment by MalcolmRobb** [comment]
mlino,
If you get/download/clone from "my" master branch, then you get a copy of whatever is currently my up to date release. If you want to incorporate your changes into my master release, then you either have to 

1) Fork your own branch and then push the changes to me so that i can update the master copy (which is what terribl just did). Ultimately I have the final say on what goes into my master copy - If I don't wan't to incorporate your changes I don't have to.
or
2) Email me your changes and i'll attempt to incorporate them into the master and I'll credit you in the commit notes- but again, I have final say on what goes into my fork/branch. This is what VK1ET is doing.
or
3) Keep your own fork (can be local or global on the server) up to date by re-syncing with my changes occasionally. This can get messey if your and my branches start to diverge significantly.

Right, lets see if I can manage to merge terribl's latest updates 

Cheers
Malcolm

**Comment by MalcolmRobb** [comment]
terribl,
Thanks for that. I've merged in your changes with only one small modification so that it compiles under Microsoft C.

I'm planning to split the file into several smaller modules soon. The main C file is approaching 4000 lines now and geting a bit too large for my liking. I have about a dozen other commits (from VK1ET) to implement first, so it may not happen for a few days. However, i plan to put all the HTTP server stuff in a single C file, so then you can modify and update it as you wish.

Cheers
Malcolm

**Comment by mindlesstux** [comment]
http://raspberry.mindlesstux.com/~adsb/mymods.diff

Made a few minor edits to this, don't know if you would want to incorporate them.  Adds a table to see the all the planes and adds the open street maps as a optional layer.

_edit_ corrected the typo on my webserver name unless you have ipv6 capability_/edit_

**Comment by MalcolmRobb** [comment]
Thanks Brian,
I'll look at it tonight. 

I'm a bit nervose about all this stuff because I don't understand HTTP, and I don't use it either, Therefore I'm unable to judge whether incorporating changes made by one user would mess up a different user. All I can test is that it compiles under M$ Visual C, and on my Raspberry Pi. 

My other concern is that modifications don't add any CPU load oberhead when they aren't being used.

I'm hoping/intending to put the IPv6 code in sometime soon.

**Comment by terribium** [comment]
Only files at 'public_html'-directory are changed and no new requests are sent to dump1090-webserver. CPU load should only increase at client side (ie. browser). (I have not tested code yet though.)

**Comment by mindlesstux** [comment]
Correct, all the changes I made are for in the browser only.  You already made the changes I made in C to kick out into json message count and last seen info.  To see the changes in play on my Pi, go to http://raspberry.mindlesstux.com/dump1090/
If that does not load, as long as you have IPv6 capability change the subdomain to raspberrypi.  The linked one passes through cloudflare to keep the bots at bay and cache most of the pages served by my Pi.  Some times something along the way gets mangled using cloudflare for me.

**Comment by terribium** [comment]
It would be more useful if all planes are shown at table. Since planes are already on map, are lat & long columns necessary? And squawk-field is missing.

**Comment by mindlesstux** [comment]
Once I think of a clean way to not add markers to planes that don't have lat/log I can easily show all planes.  I was debating on if I should keep showing the lat/long, but I do know I missed the squawk field.  My bit of add kicked in and I went off thinking how to color the aircraft based on altitude so it looks a bit more useful at a glance.  Also thinking on how to cleanly allow one or more KML files with out hardcoding them in.

**Comment by MalcolmRobb** [comment]
I've recently merged my work this week into the master copy. Much of this is a result either directly or indirectly to an EMAIL received from VK1ET. Thanks John,

Anyhow, the (a) structhre now contains a bFlags member which contains 16 bits indicating which fields in the rest of the structure contain valid data. I have no idea how to do it, but if you export either the whole bFlags member, or specifically (bFlags & MODES_ACFLAGS_LATLON_VALID) to your HTML code, then you will be able to distinguish positionless from position known aircraft.

Oh - forgot to say, Squawk is vital for military users. Since most military aircraft don't transmit their positions, the only thing you can deduce is their callsign, altitude and squawk. The squawk identifies the controlling agency and therefore tells you what VHF/UHF ATC frequencies to lisen to. So please don't remove squawk display.

**Comment by terribium** [comment]
Merged bdavenports table and 2 new json-feed fields (validposition and validtrack) on my repo. There are still few glitches to fix before I can send you a pull request.

**Comment by MalcolmRobb** [comment]
No rush. QF001 has been cancelled from DBX to LHR due to a broken windscreen. I've now got to meet Ethiad 003 at LHR 18:40 tonight.

**Pull request merged**
